let money = 30000;
let income = "Фриланс";
let addExpenses = "Налоги, Электричество, Продукты";
let deposit = false;
let mission = 150000;
let period = 12;
let budgetDay = money / 30;
// alert("Hello");
// console.log("World");
console.log(typeof money);
console.log(typeof income);
console.log(typeof deposit);
console.log(addExpenses.length);
console.log("Период равен " + period + " месяцев");
console.log("Цель заработать " + mission + " рублей");
console.log(addExpenses.toLowerCase().split(", "));
console.log(budgetDay);
